---
language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
before_install:
- sudo apt-get install python-nose
install:
- python setup.py -q install
script: nosetests
env:
  global:
  - secure: ! 'avIbOFLzFalK/uuyJEI7trBJX271arugm7DGQ4fcuIs7D5RsWFeXutIMesfH

      kxLn9LkMWBMnS4AItWgxYxa49c+w5J3Ql0fqjESVKxbYBHWCQzh39TNSjSXV

      151C5OeA8323Nn/xtZqqdI/xCHubQZODPVidvOFUsvLDn9y9r6Q='
